services:
  api:
   build:
     context: .
   env_file: .env
   ports:
     - "9090:9090"
   expose:
     - 9090
   depends_on:
     - db
   networks:
      my_network:

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
      POSTGRES_DB: dataentry
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      my_network:
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  my_network:

volumes:
  db:
